[env:esp32-c3-devkit-lipo]
platform = espressif32
board = esp32-c3-devkit-lipo
framework = arduino

monitor_speed = 115200
upload_speed = 460800

build_flags =
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1

monitor_filters = esp32_exception_decoder