M48
; DRILL file {KiCad 7.0.9-7.0.9~ubuntu22.04.1} date  9.01.2026 (пт) 16:00:17
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-01-09T16:00:17+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.9-7.0.9~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.600
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.300
%
G90
G05
T1
X11.969Y6.086
X17.749Y6.086
T2
X10.16Y19.685
X17.78Y19.685
T3
X3.81Y34.29
X3.81Y3.81
X24.13Y34.29
X24.13Y3.81
T0
M30
